name: Compile LaTeX Reports

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/xu-cheng/texlive-alpine:latest

    steps:
    - uses: actions/checkout@v6

    - name: Compile reports
      run: python3 compile_reports.py

    - name: Compile main.tex
      run: latexmk -lualatex -interaction=nonstopmode -file-line-error -shell-escape main.tex

    - name: Get date
      id: date
      run: echo "date=$(date +'%Y-%m-%dT%H-%M')" >> $GITHUB_OUTPUT

    - name: Upload main.pdf artifact
      uses: actions/upload-artifact@v7
      with:
        name: main-report-${{ github.event.pull_request.user.login }}-${{ steps.date.outputs.date }}
        path: main.pdf
        if-no-files-found: error
